//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace area23.at.mono.rpncalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPNCalc.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string action_about {
            get {
                return ResourceManager.GetString("action_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string action_continue {
            get {
                return ResourceManager.GetString("action_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string action_help {
            get {
                return ResourceManager.GetString("action_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load calculation.
        /// </summary>
        internal static string action_load {
            get {
                return ResourceManager.GetString("action_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string action_options {
            get {
                return ResourceManager.GetString("action_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save calculation.
        /// </summary>
        internal static string action_save {
            get {
                return ResourceManager.GetString("action_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenShot.
        /// </summary>
        internal static string action_screenshot {
            get {
                return ResourceManager.GetString("action_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string action_start {
            get {
                return ResourceManager.GetString("action_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string action_stop {
            get {
                return ResourceManager.GetString("action_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPNCalc.Web.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back_button {
            get {
                return ResourceManager.GetString("back_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string bContinue_text {
            get {
                return ResourceManager.GetString("bContinue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string bHelp_text {
            get {
                return ResourceManager.GetString("bHelp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string bStart_text {
            get {
                return ResourceManager.GetString("bStart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string bStop_text {
            get {
                return ResourceManager.GetString("bStop_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudio 2022 C# 4.8.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close calculation.
        /// </summary>
        internal static string close_game {
            get {
                return ResourceManager.GetString("close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty card.
        /// </summary>
        internal static string color_e {
            get {
                return ResourceManager.GetString("color_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♥.
        /// </summary>
        internal static string color_h {
            get {
                return ResourceManager.GetString("color_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♦.
        /// </summary>
        internal static string color_k {
            get {
                return ResourceManager.GetString("color_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nocolor.
        /// </summary>
        internal static string color_n {
            get {
                return ResourceManager.GetString("color_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♠.
        /// </summary>
        internal static string color_p {
            get {
                return ResourceManager.GetString("color_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♣.
        /// </summary>
        internal static string color_t {
            get {
                return ResourceManager.GetString("color_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string colorDelimiter {
            get {
                return ResourceManager.GetString("colorDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default mode.
        /// </summary>
        internal static string default_mode {
            get {
                return ResourceManager.GetString("default_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending game!.
        /// </summary>
        internal static string ending_game {
            get {
                return ResourceManager.GetString("ending_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english cards.
        /// </summary>
        internal static string english_cards {
            get {
                return ResourceManager.GetString("english_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close game..
        /// </summary>
        internal static string exception_cannot_close_game {
            get {
                return ResourceManager.GetString("exception_cannot_close_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic SchnapsNet application exception..
        /// </summary>
        internal static string exception_generic_schnapsexception {
            get {
                return ResourceManager.GetString("exception_generic_schnapsexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty and enough !.
        /// </summary>
        internal static string fourty_and_enough {
            get {
                return ResourceManager.GetString("fourty_and_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forty in.
        /// </summary>
        internal static string fourty_in_color {
            get {
                return ResourceManager.GetString("fourty_in_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to french cards.
        /// </summary>
        internal static string french_cards {
            get {
                return ResourceManager.GetString("french_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to german cards.
        /// </summary>
        internal static string german_cards {
            get {
                return ResourceManager.GetString("german_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/schnapslet.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnapslet v2.23.43 - Pre Alpha Release
        ///Implementation of the card game Schnapsen as a simple Asp.Net WebApp
        ///by Heinrich Elsigan (heinrich.elsigan@area23.at)
        ///
        ///Functionality:
        ///The game is designed to play against the computer.
        ///When it is your turn, you can play a card by clicking on the card icon.
        ///Other options, such as &quot;Exchange Atou&quot; or &quot;Announce a pair in [CardColor]&quot; 
        ///are possible via the buttons below the card symbols; 
        ///these options must be chosen before playing a card!
        ///When it is the computer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap deck with fist to start..
        /// </summary>
        internal static string image_fist {
            get {
                return ResourceManager.GetString("image_fist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take half of merged deck to start..
        /// </summary>
        internal static string image_take {
            get {
                return ResourceManager.GetString("image_take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last trick: you win!.
        /// </summary>
        internal static string last_hit_you_have_won {
            get {
                return ResourceManager.GetString("last_hit_you_have_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polish mode.
        /// </summary>
        internal static string polish_mode {
            get {
                return ResourceManager.GetString("polish_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string sPoints {
            get {
                return ResourceManager.GetString("sPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string sRest {
            get {
                return ResourceManager.GetString("sRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tDbg_text {
            get {
                return ResourceManager.GetString("tDbg_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.1.2.
        /// </summary>
        internal static string version_name {
            get {
                return ResourceManager.GetString("version_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/rpncalc.
        /// </summary>
        internal static string wiki_uri {
            get {
                return ResourceManager.GetString("wiki_uri", resourceCulture);
            }
        }
    }
}
